#!/bin/bash

curTime=`date +"%Y%m%d-%H%M%S"`
for SUBJID in `cat ~/516/subids.txt`; do
   sbatch \
   -o ~/logfiles/${curTime}-t1/o-${SUBJID}.txt \
   -e ~/logfiles/${curTime}-t1/e-${SUBJID}.txt \
   ~/516/scripts/freesurfer_job.sh \
   ${SUBJID}
   sleep 1
done
