#!/bin/bash

curTime=`date +"%Y%m%d-%H%M%S"`
mkdir -p ~/logfiles/EDSD/${curTime}-t1
for SUBJID in `cat ~/516/subids.txt`; do
  sbatch \
  -o ~/logfiles/EDSD/${curTime}-t1/o-${SUBJID}.txt \
  -e ~/logfiles/EDSD/${curTime}-t1/e-${SUBJID}.txt \
  ~/516/scripts/preprocess_job.sh \
  ${SUBJID}
  sleep 1
done
