#!/bin/bash

curTime=`date +"%Y%m%d-%H%M%S"`
mkdir -p ~/logfiles/EDSD/${curTime}-t1
for i in `cat ~/516/subids.txt`; do
  sbatch \
  -o ~/logfiles/EDSD/${curTime}-t1/o-${i}.txt \
  -e ~/logfiles/EDSD/${curTime}-t1/e-${i}.txt \
  ~/516/scripts/preprocess_job.sh \
  ${i}
  sleep 1
done
