#!/bin/bash

#SBATCH --time=00:30:00 # walltime
#SBATCH --ntasks=1 # number of processor cores (i.e. tasks)
#SBATCH --nodes=1 # number of nodes
#SBATCH --mem-per-cpu=16384M # memory per CPU core

cd ~/516/data/derivative/pDWI/${1}
bet dwi_epi_b0.nii.gz dwi_epi_b0 -f 0.5 -g 0 -m
bet dwi_epi_b0.nii.gz dwi_epi_b0 -f 0.5	-g 0 -m

dtifit \
--data=dwi_epi.nii.gz \
--out=dti \
--mask=dwi_epi_b0_mask.nii.gz \
--bvecs=dwi_eddy.eddy_rotated_bvecs \
--bvals=dwi.bval \
--save_tensor
