#!/bin/bash

curTime=`date +"%Y%m%d-%H%M%S"`
mkdir -p ~/logfiles/EDSD/${curTime}-FS
for subid in `cat ~/516/subids.txt`; do
   sbatch \
   -o ~/logfiles/EDSD/${curTime}-FS/o-${subid}.txt \
   -e ~/logfiles/EDSD/${curTime}-FS/e-${subid}.txt \
   ~/516/scripts/freesurfer_job.sh \
   ${subid}
   sleep 1
done
