#!/bin/bash

#SBATCH --time=30:00:00   # walltime
#SBATCH --ntasks=1   # number of processor cores (i.e. tasks)
#SBATCH --nodes=1   # number of nodes
#SBATCH --mem-per-cpu=16384M  # memory per CPU core


# LOAD ENVIRONMENTAL VARIABLES
freesurfer-dev

# INSERT CODE, AND RUN YOUR PROGRAMS HERE
cd ~/516/data/derivative/${i}/

recon-all \
-subjid ${i} \
-i ${i}_T1w.nii.gz \
-wsatlas \
-all \
-bigventricles \
-sd ~/516/data/FS_subjects_bv/${i}/
