#!/bin/bash

#SBATCH --time=06:00:00 # walltime
#SBATCH --ntasks=1 # number of processor cores (i.e. tasks)
#SBATCH --nodes=1 # number of nodes
#SBATCH --mem-per-cpu=16384M # memory per CPU core

DERIV=~/516/data
cd ~/516/data/derivative/pDWI/${1}
bet dwi_eddy_b0.nii.gz tmp -f 0.3 -g 0 -m
bet tmp.nii.gz dwi_eddy_b0 -f 0.3 -g 0 -m
rm tmp*

mri_convert ${DERIV}/FS_subjects_bv/${1}/mri/brainmask.mgz t1.nii.gz

antsRegistrationSynQuick.sh \
-d 3 \
-f dwi_eddy_b0.nii.gz \
-m t1.nii.gz \
-o T1toEddyB0_ \
-t a

antsRegistrationSyn.sh \
-d 3 \
-f T1toEddyB0_Warped.nii.gz \
-m dwi_eddy_b0.nii.gz \
-o dwi_epi_ \
-t so

antsApplyTransforms \
--dimensionality 3 \
--input-image-type 3 \
--input dwi_eddy.nii.gz \
--output dwi_epi.nii.gz \
--reference-image T1toEddyB0-Warped.nii.gz \
--interpolation Bspline \
--transform dwi_epi_1Warp.nii.gz
